name: ci

on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, labeled, unlabeled, synchronize ]

jobs:
  analysis-community-charts-common:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-java@v3.6.0
        with:
          java-version: 11
          distribution: temurin
      - uses: subosito/flutter-action@v2.8.0
        with:
          cache: true
      - name: Version
        run: flutter doctor -v
      - name: Install dependencies
        run: dart pub get
        working-directory: ${{ github.workspace }}/community_charts_common
      - name: Linter
        run: flutter analyze
        working-directory: ${{ github.workspace }}/community_charts_common
  analysis-community-charts-flutter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-java@v3.6.0
        with:
          java-version: 11
          distribution: temurin
      - uses: subosito/flutter-action@v2.8.0
        with:
          cache: true
      - name: Version
        run: flutter doctor -v
      - name: Install dependencies
        run: flutter pub get
        working-directory: ${{ github.workspace }}/community_charts_flutter
      - name: Linter
        run: flutter analyze
        working-directory: ${{ github.workspace }}/community_charts_flutter
  formatting-community-charts-common:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-java@v3.6.0
        with:
          java-version: 11
          distribution: temurin
      - uses: subosito/flutter-action@v2.8.0
        with:
          cache: true
      - name: Format
        run: flutter format -n --set-exit-if-changed .
        working-directory: ${{ github.workspace }}/community_charts_common
  formatting-community-charts-flutter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-java@v3.6.0
        with:
          java-version: 11
          distribution: temurin
      - uses: subosito/flutter-action@v2.8.0
        with:
          cache: true
      - name: Format
        run: flutter format -n --set-exit-if-changed .
        working-directory: ${{ github.workspace }}/community_charts_flutter
        # TODO: migrate tests to null-safety
#  test-community-charts-common:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3.1.0
#      - uses: actions/setup-java@v3.6.0
#        with:
#          java-version: 11
#          distribution: temurin
#      - uses: subosito/flutter-action@v2.8.0
#        with:
#          cache: true
#      - name: Tests
#        run: flutter test
#        working-directory: ${{ github.workspace }}/community_charts_common
  test-community-charts-flutter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-java@v3.6.0
        with:
          java-version: 11
          distribution: temurin
      - uses: subosito/flutter-action@v2.8.0
        with:
          cache: true
      - name: Tests
        run: flutter test
        working-directory: ${{ github.workspace }}/community_charts_flutter